//
//	RXScriptCommandAliases.h
//	rivenx
//
//	Created by Jean-Francois Roy on 07/12/2008.
//	Copyright 2008 MacStorm. All rights reserved.
//

#define RX_COMMAND_GOTO_CARD 2
#define RX_COMMAND_PLAY_LOCAL_SOUND 4
#define RX_COMMAND_ENABLE_HOTSPOT 9
#define RX_COMMAND_DISABLE_HOTSPOT 10
#define RX_COMMAND_CLEAR_SLST 12
#define RX_COMMAND_SCHEDULE_TRANSITION 18
#define RX_COMMAND_REFRESH 19
#define RX_COMMAND_DISABLE_SCREEN_UPDATES 20
#define RX_COMMAND_ENABLE_SCREEN_UPDATES 21
#define RX_COMMAND_DISABLE_MOVIE 28
#define RX_COMMAND_PLAY_MOVIE_BLOCKING 32
#define RX_COMMAND_PLAY_MOVIE 33
#define RX_COMMAND_ACTIVATE_PLST 39
#define RX_COMMAND_ACTIVATE_SLST 40
#define RX_COMMAND_ACTIVATE_PLAY_MLST 41
#define RX_COMMAND_ACTIVATE_BLST 43
#define RX_COMMAND_ACTIVATE_MLST 46
